.TH HELLO 1 "John Soupir 19 September 2020"
.SH NAME
hello - Simple hello world program with user input.
.SH SYNOPSIS
\fBhello\fP \fI<some_word>\fP
.SH DESCRIPTION
\fBhello\fP prints "Hello <some_word> world". 
It accepts an argument of one word.
If no user input is found or if more or less than one argument is given the program will exit with an error message.
It was written in C using vim and compiled with gcc.
.SS Options
.TP
THERE ARE NO OPTIONS.
.SH FILES
.TP

There are no files.
.SH "SEE ALSO"
gcc, vim
.SH BUGS
There are no bugs, only features!
