.TH VICE 1 "John Soupir 23 Dec 2020"
.SH NAME
Vice - Create and run ngspice simulations VERY quickly and easily.
.SH SYNOPSIS
\fBvice\fP \fI<name_of_simulation> <template>\fP
.SH DESCRIPTION
\fBvice\fP is a tool for making changes and running NGSPICE simulations very quickly. When used to \n 
open a file it will open in the chosen editor, then imediatly upon exiting the editor the simulation will be run. There are also templates for creating new net files. 


.SS Options
.TP
vice <name_of_file> - opens specified file, then runs simulation upon exiting editor.
vice <name_of_file> <template> - creates new file from given template
vice ls - list available template files
.SH FILES
.TP
vice (if auto installed) should be found in /usr/local/bin/
.SH "SEE ALSO"
csaw, vix
.SH BUGS
There are no bugs, only features!
