.TH VICE 1 "John Soupir 23 Dec 2020"
.SH NAME
Vice - Create and run ngspice simulations VERY quickly and easily.
.SH SYNOPSIS
\fBvice\fP \fI<name_of_simulation> <template>\fP
.SH DESCRIPTION
\fBvix\fP creates a file with #!/bin/bash at the top, makes it executable and opens it with vim. All with a single command. \n 
If a given file already exists vix will open it and not overwrite it. 


.SS Options
.TP
vix <name_of_file> o - If you wish to overwrite an existing file of the same name include an "o" at the end of your command.
.SH FILES
.TP
vix (if auto installed) should be found in /usr/local/bin/
.SH "SEE ALSO"
csaw, vice
.SH BUGS
There are no bugs, only features!
