#!/bin/bash

#csaw is a tool for creating blank C programs quickly.
#vix version 1.0.0 from Nov 14th 2020
#by John Soupir


#usage if no arguments
if [ $# -lt 1  ]; then
	echo "	USAGE: $0 filename.c"
	echo "	csaw is a tool for creating blank C programs quickly."
	echo "	csaw creates a file with the specified name,"
	echo "	inserts the standard libs, a main function, and opens with vim."
	echo ""
	echo "	Example: $0 mycode.c"
	echo "	will create a file \"myscript.c\" and open"
	echo "	the file with vim."
	echo ""
	echo "	Note that existing files can be overwritten with o"
	echo "	Example: $0 mycode.c o"
	exit
fi


#Looking for a file in the current directory with the same name as $1"
SEARCH=$(ls $pwd | grep $1)

#debug output
#echo "$SEARCH"

#Overwrite or open the existing file.
if [[  $2 = "o" ]]; then
	echo "o detected. File overwritten."
	echo "#!/bin/bash" > $1

	
echo "	#include <stdio.h>

        int main(int argc, char **argv){ 
	if(argc != 2){
	   printf ("\a\a\a\a\a\a\a\a\a\a\aDude, you need to supply a single argument man. Peace out! \n");

	
	   return 1;

	}

	printf ("hello %s  world\n", argv[1]);

	return 0;
	//Comment


	}

		

	chmod +x $1
	vim $1
	exit
elif [[ $1  = $SEARCH ]]; then
	echo "File already exists! Opening with vim."
	vim $1
	exit
fi

#If the file does not exist, create it.
echo "#!/bin/bash" >> $1
chmod +x $1
vim $1


