#!/bin/bash


echo "Install full toolkit?"
echo "Y/n?"
read OPTION
if [[ $OPTION = "n" ]]; then
	exit
fi

echo "Installing everything..."

sudo cp vix vice push pull pack /usr/local/bin/

echo "Done."

