#!/bin/bash


echo "________________________________________________________________"                                                               
echo ' _____ ___   ___  _     _  _____ _____    __            '
echo '|_   _/ _ \ / _ \| |   | |/ /_ _|_   _|  / _| ___  _ __ '
echo '  | || | | | | | | |   |   / | |  | |   | |_ / _ \| \__|'
echo '  | || |_| | |_| | |___|   \ | |  | |   |  _| (_) | |   '
echo '  |_| \___/ \___/|_____|_|\_\___| |_|   |_|  \___/|_|   '
echo""                                                        
echo ' _____ _   _  ____ ___ _   _ _____ _____ ____  ___ _   _  ____ '
echo '| ____| \ | |/ ___|_ _| \ | | ____| ____|  _ \|_ _| \ | |/ ___|'
echo '|  _| |  \| | |  _ | ||  \| |  _| |  _| | |_) || ||  \| | |  _ '
echo '| |___| |\  | |_| || || |\  | |___| |___|  _ < | || |\  | |_| |'
echo '|_____|_| \_|\____|___|_| \_|_____|_____|_| \_\___|_| \_|\____|'
echo "by J.S.                                                    V1.5"                                                               
echo "________________________________________________________________"                                                               
echo ""                                                               
echo "Install full toolkit? (about 10Kb)"
echo "Y/n?"
read OPTION
if [[ $OPTION = "n" || $OPTION = "N" ]]; then
	#add selective installation menu
	echo "Installation stopped."
	exit
fi

echo "Installing everything..."

sudo cp stat vix vice push pull pack /usr/local/bin/

echo "Done."

