#!/bin/bash

#This is a tool for creating ngspice network files from a template, editing them, and then running the file all with one command.
#Version No. 1.1.2 from 10-16-2020
#by John Soupir


#USER_SETTINGS
#Change text editor
EDITOR=vim
#Run simulation on exit? 1=yes 0=no
OPEN=1
#Default template when no option is given.
#Current templates: default=default, extra help=h
TEMPLATE=default
#END_OF_SETTINGS


#Search for existing file
SEARCH=$(ls | grep $1)

#Print usage if no argument
if [ $# -lt 1  ]; then
        echo "  USAGE: $0 <filename> <template>"
        echo "  $0 is a tool for creating/opening ngspice files"
        echo "  and editing them with one command."
        echo ""
        echo "  Example: $0 mycircuit.net"
        echo "  will create an ngspice file from the default template"
        echo "  and open the file with your default editor. If the file already exists"
        echo "  it will be opened and not overwritten."
	echo "  After exiting it will run the simulation. "
	echo ""
	echo "  Use the optional <template> argument to call a specific template."
	echo "  Example: $0 mycircuit.net h"
	echo "  will do the same as the last example, but will use the extra help template."
        exit
fi

#If user called template, use it.
if [ $# = 2 ]; then
	TEMPLATE=$2
fi

#Check if existing file was found.
if [ "$SEARCH" = "$1" ]; then
	echo "$1 already exists! Opening in $EDITOR"
	$EDITOR $1
	if [ $OPEN = "1" ]; then
		ngspice < $1
	fi
	exit
fi


#Use requested template
if [ $TEMPLATE = "default" ]; then
#DEFAULT TEMPLATE
echo "Creating $1 with deafult template."
echo "*$1" > $1
echo '' >> $1
echo 'V1 a 0 10' >> $1
echo 'V01 b 0 0' >> $1
echo 'R1 a b 5' >> $1
echo '' >> $1
echo '' >> $1
echo '.control' >> $1
echo 'op' >> $1
echo 'listing e' >> $1
echo '' >> $1
echo '' >> $1
echo '*analysis requests' >> $1
echo 'let Vs = v(a)' >> $1
echo 'let vR1 = v(a,b)' >> $1
echo 'let Is = i(V1)' >> $1
echo 'let I01 = i(V01)' >> $1
echo '' >> $1
echo '' >> $1
echo '*output requests' >> $1
echo 'print Vs vR1 Is I01' >> $1
echo '' >> $1
echo '.endc' >> $1
echo '.end' >> $1
echo '' >> $1
echo "Opened in $EDITOR"
$EDITOR $1
fi

#Use requested template
if [ $TEMPLATE = "h" ]; then
#EXTRA HELP TEMPLATE
echo "Creating $1 with help template."
echo "*$1" > $1
echo '*' >> $1
echo '*_____________Extra help_____________' >> $1
echo '*VCCS = G1 N+ N- NC+ NC- VALUE ' >> $1
echo '*where nc+ and nc- are the controlling nodes' >> $1
echo '' >> $1
echo '*VCVS = E1 N+ N- NC+ NC- VALUE' >> $1
echo '*where nc+ and nc- are the controlling nodes' >> $1
echo '' >> $1
echo '*CCCS = F1 N+ N- VNAM VALUE' >> $1
echo '*where VNAM is voltage source w/controlling current' >> $1
echo '' >> $1
echo '*CCVS = H1 N+ N- NNAM VALUE' >> $1
echo '*where VNAM is voltage source w/controlling current' >> $1
echo '*____________________________________' >> $1
echo '' >> $1
echo 'V1 a 0 10' >> $1
echo 'V01 b 0 0' >> $1
echo 'R1 a b 5' >> $1
echo '' >> $1
echo '' >> $1
echo '.control' >> $1
echo 'op' >> $1
echo 'listing e' >> $1
echo '' >> $1
echo '' >> $1
echo '*analysis requests' >> $1
echo 'let Vs = v(a)' >> $1
echo 'let vR1 = v(a,b)' >> $1
echo 'let Is = i(V1)' >> $1
echo 'let I01 = i(V01)' >> $1
echo '' >> $1
echo '' >> $1
echo '*output requests' >> $1
echo 'print Vs vR1 Is I01' >> $1
echo '' >> $1
echo '.endc' >> $1
echo '.end' >> $1
echo '' >> $1
echo "Opened in $EDITOR"
$EDITOR $1
fi

#Run simulation if selected
if [ $OPEN = "1" ]; then
ngspice < $1
fi
