#!/bin/bash

#vix (short for vim executable) is a tool for creating blank bash scripts very quickly. It creates a file with #!/bin/bash, makes it executable, and opens it in vim.
#vix version 2.1.2 from Oct 18th 2020
#by John Soupir


#usage if no arguments
if [ $# -lt 1  ]; then
	echo "	USAGE: $0 filename"
	echo "	Vix is a tool for creating blank bash scripts"
	echo "	very quickly."
	echo "	Vix creates a file with the specified name,"
	echo "	inserts #!/bin/bash at the top, then makes"
	echo "  the file executable and opens it in vim."
	echo ""
	echo "	Example: $0 myscript"
	echo "	will create an executable \"myscript.sh\" and open"
	echo "	the file with vim."
	echo ""
	echo "	Note that existing files can be overwritten with o"
	echo "	Example: $0 myscript o"
	exit
fi


#Looking for a file in the current directory with the same name as $1"
SEARCH=$(ls $pwd | grep $1)

#debug output
#echo "$SEARCH"

#Overwrite or open the existing file.
if [[  $2 = "o" ]]; then
	echo "o detected. File overwritten."
	echo "#!/bin/bash" > $1
	chmod +x $1
	vim $1
	exit
elif [[ $1  = $SEARCH ]]; then
	echo "File already exists! Opening with vim."
	vim $1
	exit
fi

#If the file does not exist, create it.
echo "#!/bin/bash" >> $1
chmod +x $1
vim $1


